
services:
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backEnd:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    image: react-app
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    stdin_open: true
    tty: true
